web:
  container_name: web
  build: .
  volumes:
    - ./drupal:/var/www/html
  ports:
    - "80:80"
  extra_hosts:
    - "axtel.local:127.0.0.1"
    - "new.axtel.local:127.0.0.1"
  links:
    - db

dbdata:
  container_name: dbdata
  image: busybox:latest
  volumes:
    - /var/lib/mysql
  command: /bin/echo

db:
  container_name: db
  image: mariadb:10
  volumes_from:
    - dbdata
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: drupal
    MYSQL_USER: drupal
    MYSQL_PASSWORD: drupal

cli:
  container_name: cli
  build: cli/.
  volumes:
    - ./drupal:/var/www/html
  ports:
  ports:
    - "9000:9000"
  extra_hosts:
  links:
    - db
    - web
